version: '3'
services:
  api:
    image: msozkan/rest-api-tutorial
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27018:27017"

  web-cli:
    image: msozkan/rest-api-tutorial
    links:
      - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
